# Generated by Django 4.2.25 on 2025-11-17 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Resume file (PDF, DOCX, or TXT)', upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt'])])),
                ('extracted_text', models.TextField(blank=True, help_text='Resume text extracted from file')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, help_text='Has text been extracted from file?')),
                ('user', models.ForeignKey(help_text='Volunteer who uploaded the resume', on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('opportunities_to_score', models.IntegerField(default=0)),
                ('opportunities_scored', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_jobs', to='resumes.resume')),
            ],
            options={
                'db_table': 'scoring_jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='Overall match score (0-100)')),
                ('skills_match', models.IntegerField(default=0, help_text='Skills alignment (0-100)')),
                ('experience_match', models.IntegerField(default=0, help_text='Experience match (0-100)')),
                ('education_match', models.IntegerField(default=0, help_text='Education match (0-100)')),
                ('grade', models.CharField(choices=[('A+', 'A+ (95-100)'), ('A', 'A (90-94)'), ('B+', 'B+ (85-89)'), ('B', 'B (80-84)'), ('C+', 'C+ (75-79)'), ('C', 'C (70-74)'), ('D', 'D (65-69)'), ('F', 'F (0-64)')], max_length=3)),
                ('recommendation', models.CharField(choices=[('highly_recommended', 'Highly Recommended'), ('recommended', 'Recommended'), ('consider', 'Consider'), ('not_recommended', 'Not Recommended')], max_length=20)),
                ('key_strength', models.TextField(help_text='Main Strength of Candidate')),
                ('concerns', models.TextField(blank=True, help_text='Potential concerns or gaps')),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('scored_by_model', models.CharField(default='gpt-4o-mini', help_text='AI Model used for Scoring', max_length=50)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_scores', to='opportunities.opportunity')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='resumes.resume')),
            ],
            options={
                'db_table': 'resume_scores',
                'ordering': ['-overall_score'],
                'indexes': [models.Index(fields=['opportunity', '-overall_score'], name='resume_scor_opportu_575826_idx'), models.Index(fields=['-overall_score'], name='resume_scor_overall_077bb4_idx')],
                'unique_together': {('resume', 'opportunity')},
            },
        ),
    ]
