# Generated by Django 4.2.25 on 2025-11-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumescore',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+ (100-95)'), ('A', 'A (94-90)'), ('B+', 'B+ (89-85)'), ('B', 'B (84-80)'), ('C+', 'C+ (79-75)'), ('C', 'C (74-70)'), ('D', 'D (69-65)'), ('F', 'F (64-0)')], max_length=3),
        ),
    ]
