# Generated by Django 4.2.25 on 2025-11-23 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0002_alter_resumescore_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescore',
            name='acceptance_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
