# Generated by Django 4.2.25 on 2025-11-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resumescore_acceptance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Matching Dashboard',
                'verbose_name_plural': '🎯 Matching Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resumes.resumescore',),
        ),
    ]
