# Generated by Django 4.2.25 on 2025-11-24 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_source_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0004_matchingdashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchingDashboard',
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scoringjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='resumescore',
            name='resume_scor_opportu_575826_idx',
        ),
        migrations.RemoveIndex(
            model_name='resumescore',
            name='resume_scor_overall_077bb4_idx',
        ),
        migrations.RenameField(
            model_name='scoringjob',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='concerns',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='education_match',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='experience_match',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='key_strength',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='scored_by_model',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='skills_match',
        ),
        migrations.RemoveField(
            model_name='scoringjob',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='scoringjob',
            name='opportunities_scored',
        ),
        migrations.RemoveField(
            model_name='scoringjob',
            name='opportunities_to_score',
        ),
        migrations.AddField(
            model_name='resumescore',
            name='education_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='experience_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='skills_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringjob',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='acceptance_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlist', 'Waitlisted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoringjob',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resume'),
        ),
    ]
