# Generated by Django 4.2.25 on 2025-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_delete_matchingdashboard_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescore',
            name='concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='education_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='experience_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='key_strength',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='scored_by_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='skills_match',
            field=models.IntegerField(default=0),
        ),
    ]
