# Generated by Django 4.2.25 on 2025-11-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
