# Generated by Django 4.2.25 on 2025-10-08 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Match score from 0.0 to 1.0')),
                ('skill_match', models.FloatField(default=0.0)),
                ('availability_match', models.FloatField(default=0.0)),
                ('interest_match', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='opportunities.opportunity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_scores',
                'ordering': ['-score'],
                'unique_together': {('volunteer', 'opportunity')},
            },
        ),
    ]
